namespace LoLFit.Core.Model
{
    public class BasicDataStatsDto
    {
        public double FlatArmorMod { get; set; }
        public double FlatAttackSpeedMod { get; set; }
        public double FlatBlockMod { get; set; }
        public double FlatCritChanceMod { get; set; }
        public double FlatCritDamageMod { get; set; }
        public double FlatExpBonus { get; set; }
        public double FlatEnergyPoolMod { get; set; }
        public double FlatEnergyRegenMod { get; set; }
        public double FlatHpPoolMod { get; set; }
        public double FlatHpRegenMod { get; set; }
        public double FlatMpPoolMod { get; set; }
        public double FlatMpRegenMod { get; set; }
        public double FlatMagicDamageMod { get; set; }
        public double FlatMovementSpeedMod { get; set; }
        public double FlatPhysicalDamageMod { get; set; }
        public double FlatSpellBlockMod { get; set; }
        public double PercentArmorMod { get; set; }
        public double PercentAttackSpeedMod { get; set; }
        public double PercentBlockMod { get; set; }
        public double PercentCritChanceMod { get; set; }
        public double PercentCritDamageMod { get; set; }
        public double PercentDodgeMod { get; set; }
        public double PercentExpBonus { get; set; }
        public double PercentHpPoolMod { get; set; }
        public double PercentHpRegenMod { get; set; }
        public double PercentLifeStealMod { get; set; }
        public double PercentMpPoolMod { get; set; }
        public double PercentMpRegenMod { get; set; }
        public double PercentMagicDamageMod { get; set; }
        public double PercentMovementSpeedMod { get; set; }
        public double PercentPhysicalDamageMod { get; set; }
        public double PercentSpellBlockMod { get; set; }
        public double PercentSpellVampMod { get; set; }
        public double RFlatArmorModPerLevel { get; set; }
        public double RFlatArmorPenetrationMod { get; set; }
        public double RFlatArmorPenetrationModPerLevel { get; set; }
        public double RFlatCritChanceModPerLevel { get; set; }
        public double RFlatCritDamageModPerLevel { get; set; }
        public double RFlatDodgeMod { get; set; }
        public double RFlatDodgeModPerLevel { get; set; }
        public double RFlatEnergyModPerLevel { get; set; }
        public double RFlatEnergyRegenModPerLevel { get; set; }
        public double RFlatGoldPer10Mod { get; set; }
        public double RFlatHpModPerLevel { get; set; }
        public double RFlatHpRegenModPerLevel { get; set; }
        public double RFlatMpModPerLevel { get; set; }
        public double RFlatMpRegenModPerLevel { get; set; }
        public double RFlatMagicDamageModPerLevel { get; set; }
        public double RFlatMagicPenetrationMod { get; set; }
        public double RFlatMagicPenetrationModPerLevel { get; set; }
        public double RFlatMovementSpeedModPerLevel { get; set; }
        public double RFlatPhysicalDamageModPerLevel { get; set; }
        public double RFlatSpellBlockModPerLevel { get; set; }
        public double RFlatTimeDeadMod { get; set; }
        public double RFlatTimeDeadModPerLevel { get; set; }
        public double RPercentArmorPenetrationMod { get; set; }
        public double RPercentArmorPenetrationModPerLevel { get; set; }
        public double RPercentAttackSpeedModPerLevel { get; set; }
        public double RPercentCooldownMod { get; set; }
        public double RPercentCooldownModPerLevel { get; set; }
        public double RPercentMagicPenetrationMod { get; set; }
        public double RPercentMagicPenetrationModPerLevel { get; set; }
        public double RPercentMovementSpeedModPerLevel { get; set; }
        public double RPercentTimeDeadMod { get; set; }
        public double RPercentTimeDeadModPerLevel { get; set; }
    }
}
