namespace LoLFit.Core.Model
{
    public class RawStats
    {
        public int Assists { get; set; }
        public int BarracksKilled { get; set; }
        public int ChampionsKilled { get; set; }
        public int CombatPlayerScore { get; set; }
        public int ConsumablesPurchased { get; set; }
        public int DamageDealtPlayer { get; set; }
        public int DoubleKills { get; set; }
        public int FirstBlood { get; set; }
        public int Gold { get; set; }
        public int GoldEarned { get; set; }
        public int GoldSpent { get; set; }
        public int Item0 { get; set; }
        public int Item1 { get; set; }
        public int Item2 { get; set; }
        public int Item3 { get; set; }
        public int Item4 { get; set; }
        public int Item5 { get; set; }
        public int Item6 { get; set; }
        public int ItemsPurchased { get; set; }
        public int KillingSprees { get; set; }
        public int LargestCriticalStrike { get; set; }
        public int LargestKillingSpree { get; set; }
        public int LargestMultiKill { get; set; }
        public int LegendaryItemCreated { get; set; }
        public int Level { get; set; }
        public int MagicDamageDealtPlayer { get; set; }
        public int MagicDamageDealtToChampions { get; set; }
        public int MagicDamageTaken { get; set; }
        public int MinionsDenied { get; set; }
        public int MinionsKilled { get; set; }
        public int NeutralMinionsKilled { get; set; }
        public int NeutralMinionsKilledEnemyJungle { get; set; }
        public int NeutralMinionsKilledYourJungle { get; set; }
        public bool NexusKilled { get; set; }
        public int NodeCapture { get; set; }
        public int NodeCaptureAssist { get; set; }
        public int NodeNeutralize { get; set; }
        public int NodeNeutralizeAssist { get; set; }
        public int NumDeaths { get; set; }
        public int NumItemsBought { get; set; }
        public int ObjectivePlayerScore { get; set; }
        public int PentaKills { get; set; }
        public int PhysicalDamageDealtPlayer { get; set; }
        public int PhysicalDamageDealtToChampions { get; set; }
        public int PhysicalDamageTaken { get; set; }
        public int QuadraKills { get; set; }
        public int SightWardsBought { get; set; }
        public int Spell1Cast { get; set; }
        public int Spell2Cast { get; set; }
        public int Spell3Cast { get; set; }
        public int Spell4Cast { get; set; }
        public int SummonSpell1Cast { get; set; }
        public int SummonSpell2Cast { get; set; }
        public int SuperMonsterKilled { get; set; }
        public int Team { get; set; }
        public int TeamObjective { get; set; }
        public int TimePlayed { get; set; }
        public int TotalDamageDealt { get; set; }
        public int TotalDamageDealtToChampions { get; set; }
        public int TotalDamageTaken { get; set; }
        public int TotalHeal { get; set; }
        public int TotalPlayerScore { get; set; }
        public int TotalScoreRank { get; set; }
        public int TotalTimeCrowdControlDealt { get; set; }
        public int TotalUnitsHealed { get; set; }
        public int TripleKills { get; set; }
        public int TrueDamageDealtPlayer { get; set; }
        public int TrueDamageDealtToChampions { get; set; }
        public int TrueDamageTaken { get; set; }
        public int TurretsKilled { get; set; }
        public int UnrealKills { get; set; }
        public int VictoryPointTotal { get; set; }
        public int VisionWardsBought { get; set; }
        public int WardKilled { get; set; }
        public int WardPlaced { get; set; }
        public bool Win { get; set; }
    }
}
